name: firebase_todo_app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  firebase_analytics: ^10.4.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.3
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
